name: Autoupdate
on:
  schedule:
    - cron: "0 1 * * *"
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: false
jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      IRECEIPTPRO_API_KEY: ${{ secrets.IRECEIPTPRO_API_KEY }}
    outputs:
      updated: ${{ steps.autoupdate.outputs.updated }}
      version: ${{ steps.autoupdate.outputs.version }}
    steps:
      - name: Сheckout repo
        id: checkout_repo
        uses: actions/checkout@v5
        with:
          path: "tmp"
          ref: "main"
      - name: Autoupdate
        id: autoupdate
        uses: siarheidudko/autoupdater@v6
        with:
          author-email: "slavianich@gmail.com"
          author-name: "Siarhei Dudko"
          working-directory: ${{ github.workspace }}/tmp
          ref: ${{ github.repository }}
          branch: "main"
          builds-and-checks: |
            npm run build
            npm test
          debug: "true"
          ignore-packages: |
            @types/node
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_VERSION: 22
      VERSION: ${{ needs.update.outputs.version }}
    needs: [update]
    if: ${{ needs.update.outputs.updated == 'true' }}
    steps:
      - name: Сheckout repo
        id: checkout_repo
        uses: actions/checkout@v6
        with:
          ref: "main"
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.update.outputs.version }}
          name: v${{ needs.update.outputs.version }}
          body_path: ${{ github.workspace }}/README.md
          repository: ireceipt-pro/js
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
